// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Restaurant.Data;

#nullable disable

namespace Restaurant.Migrations
{
    [DbContext(typeof(RestaurantContext))]
    [Migration("20251201082137_productWithImage")]
    partial class productWithImage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Restaurant.Models.Bestelling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Aantal")
                        .HasColumnType("integer");

                    b.Property<string>("Opmerking")
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("ReservatieId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TijdstipBestelling")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReservatieId");

                    b.HasIndex("StatusId");

                    b.ToTable("Bestelling", (string)null);
                });

            modelBuilder.Entity("Restaurant.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actief")
                        .HasColumnType("boolean");

                    b.Property<string>("Naam")
                        .HasColumnType("text");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Categorie", (string)null);
                });

            modelBuilder.Entity("Restaurant.Models.CategorieType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actief")
                        .HasColumnType("boolean");

                    b.Property<string>("Naam")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CategorieType", (string)null);
                });

            modelBuilder.Entity("Restaurant.Models.CustomUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Achternaam")
                        .HasColumnType("text");

                    b.Property<bool>("Actief")
                        .HasColumnType("boolean");

                    b.Property<string>("Adres")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ForgotPasswordResetToken")
                        .HasColumnType("uuid");

                    b.Property<string>("Gemeente")
                        .HasColumnType("text");

                    b.Property<string>("Huisnummer")
                        .HasColumnType("text");

                    b.Property<int>("LandId")
                        .HasColumnType("integer");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("PassWordResetCodeExpiry")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PassWordResetCodeHash")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Postcode")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Voornaam")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LandId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Restaurant.Models.Land", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actief")
                        .HasColumnType("boolean");

                    b.Property<string>("Naam")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Land", (string)null);
                });

            modelBuilder.Entity("Restaurant.Models.Mail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<string>("Naam")
                        .HasColumnType("text");

                    b.Property<string>("Onderwerp")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Mail", (string)null);
                });

            modelBuilder.Entity("Restaurant.Models.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Waarde")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Parameter", (string)null);
                });

            modelBuilder.Entity("Restaurant.Models.PrijsProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumVanaf")
                        .HasColumnType("date");

                    b.Property<decimal>("Prijs")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("PrijsProduct", (string)null);
                });

            modelBuilder.Entity("Restaurant.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actief")
                        .HasColumnType("boolean");

                    b.Property<string>("AfbeeldingNaam")
                        .HasColumnType("text");

                    b.Property<string>("AllergenenInfo")
                        .HasColumnType("text");

                    b.Property<string>("Beschrijving")
                        .HasColumnType("text");

                    b.Property<int>("CategorieId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSuggestie")
                        .HasColumnType("boolean");

                    b.Property<string>("Naam")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("Restaurant.Models.Reservatie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AantalPersonen")
                        .HasColumnType("integer");

                    b.Property<bool>("Betaald")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("Datum")
                        .HasColumnType("date");

                    b.Property<int>("EvaluatieAantalSterren")
                        .HasColumnType("integer");

                    b.Property<string>("EvaluatieOpmerkingen")
                        .HasColumnType("text");

                    b.Property<bool>("IsAanwezig")
                        .HasColumnType("boolean");

                    b.Property<string>("KlantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Opmerking")
                        .HasColumnType("text");

                    b.Property<int>("TijdSlotId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("WelkomstmailVerstuurdOp")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("KlantId");

                    b.HasIndex("TijdSlotId");

                    b.ToTable("Reservatie", (string)null);
                });

            modelBuilder.Entity("Restaurant.Models.Sluitingsdag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Datum")
                        .HasColumnType("date");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sluitingsdag", (string)null);
                });

            modelBuilder.Entity("Restaurant.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actief")
                        .HasColumnType("boolean");

                    b.Property<string>("Naam")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Status", (string)null);
                });

            modelBuilder.Entity("Restaurant.Models.Tafel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AantalPersonen")
                        .HasColumnType("integer");

                    b.Property<bool>("Actief")
                        .HasColumnType("boolean");

                    b.Property<int>("MinAantalPersonen")
                        .HasColumnType("integer");

                    b.Property<string>("QrBarcode")
                        .HasColumnType("text");

                    b.Property<string>("TafelNummer")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tafel", (string)null);
                });

            modelBuilder.Entity("Restaurant.Models.TafelLijst", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ReservatieId")
                        .HasColumnType("integer");

                    b.Property<int>("TafelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReservatieId");

                    b.HasIndex("TafelId");

                    b.ToTable("TafelLijst", (string)null);
                });

            modelBuilder.Entity("Restaurant.Models.Tijdslot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actief")
                        .HasColumnType("boolean");

                    b.Property<string>("Naam")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TijdSlot", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Restaurant.Models.CustomUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Restaurant.Models.CustomUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.Models.CustomUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Restaurant.Models.CustomUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Restaurant.Models.Bestelling", b =>
                {
                    b.HasOne("Restaurant.Models.Product", "Product")
                        .WithMany("Bestellingen")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Restaurant.Models.Reservatie", "Reservatie")
                        .WithMany("Bestellingen")
                        .HasForeignKey("ReservatieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Restaurant.Models.Status", "Status")
                        .WithMany("Bestellingen")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Reservatie");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Restaurant.Models.Categorie", b =>
                {
                    b.HasOne("Restaurant.Models.CategorieType", "Type")
                        .WithMany("Categorieen")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Restaurant.Models.CustomUser", b =>
                {
                    b.HasOne("Restaurant.Models.Land", "Land")
                        .WithMany("Gebruikers")
                        .HasForeignKey("LandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Land");
                });

            modelBuilder.Entity("Restaurant.Models.PrijsProduct", b =>
                {
                    b.HasOne("Restaurant.Models.Product", "Product")
                        .WithMany("PrijsProducten")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Restaurant.Models.Product", b =>
                {
                    b.HasOne("Restaurant.Models.Categorie", "Categorie")
                        .WithMany("Producten")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("Restaurant.Models.Reservatie", b =>
                {
                    b.HasOne("Restaurant.Models.CustomUser", "CustomUser")
                        .WithMany("Reservaties")
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Restaurant.Models.Tijdslot", "Tijdslot")
                        .WithMany("Reservaties")
                        .HasForeignKey("TijdSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomUser");

                    b.Navigation("Tijdslot");
                });

            modelBuilder.Entity("Restaurant.Models.TafelLijst", b =>
                {
                    b.HasOne("Restaurant.Models.Reservatie", "Reservatie")
                        .WithMany("Tafellijsten")
                        .HasForeignKey("ReservatieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Restaurant.Models.Tafel", "Tafel")
                        .WithMany("TafelLijsten")
                        .HasForeignKey("TafelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reservatie");

                    b.Navigation("Tafel");
                });

            modelBuilder.Entity("Restaurant.Models.Categorie", b =>
                {
                    b.Navigation("Producten");
                });

            modelBuilder.Entity("Restaurant.Models.CategorieType", b =>
                {
                    b.Navigation("Categorieen");
                });

            modelBuilder.Entity("Restaurant.Models.CustomUser", b =>
                {
                    b.Navigation("Reservaties");
                });

            modelBuilder.Entity("Restaurant.Models.Land", b =>
                {
                    b.Navigation("Gebruikers");
                });

            modelBuilder.Entity("Restaurant.Models.Product", b =>
                {
                    b.Navigation("Bestellingen");

                    b.Navigation("PrijsProducten");
                });

            modelBuilder.Entity("Restaurant.Models.Reservatie", b =>
                {
                    b.Navigation("Bestellingen");

                    b.Navigation("Tafellijsten");
                });

            modelBuilder.Entity("Restaurant.Models.Status", b =>
                {
                    b.Navigation("Bestellingen");
                });

            modelBuilder.Entity("Restaurant.Models.Tafel", b =>
                {
                    b.Navigation("TafelLijsten");
                });

            modelBuilder.Entity("Restaurant.Models.Tijdslot", b =>
                {
                    b.Navigation("Reservaties");
                });
#pragma warning restore 612, 618
        }
    }
}
